frontend/models/Books.php
<?php

namespace frontend\models;

use yii\db\ActiveRecord;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * This is the model class for table "books".
 *
 * @property int $id
 * @property string $appellation
 * @property string $text
 * @property int $author_id
 * @property int $hero_id
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property Author $author
 */
class Books extends ActiveRecord
{
    public static function tableName()
    {
        return 'books';
    }

    public function rules()
    {
        return [
            [['appellation', 'author_id'], 'required'],
            [['text'], 'string'],
            [['author_id', 'hero_id'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['appellation'], 'string', 'max' => 255],
            [['author_id'], 'exist', 'skipOnError' => true, 'targetClass' => Author::className(), 'targetAttribute' => ['author_id' => 'id']],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'appellation' => 'Appellation',
            'text' => 'Text',
            'author_id' => 'Author',
            'hero_id' => 'Hero',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'authorName' => 'Author Name',
        ];
    }

    public function getAuthor()
    {
        return $this->hasOne(Author::className(), ['id' => 'author_id']);
    }

    public function getHero()
    {
        return $this->hasOne(Hero::className(), ['id' => 'hero_id']);
    }

    public function getAuthorName()
    {

        return $this->getAuthor()->one()->name;
    }

    public function getHistory()
    {
        return $this->hasMany(BooksHistory::className(), ['book_id' => 'id']);
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'value' => function () {
                    return new Expression('NOW()');
                }],
        ];
    }
}

frontend/controllers/AuthorController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Author;
use frontend\models\SearchAuthor;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AuthorController implements the CRUD actions for author model.
 */
class AuthorController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all author models.
     * @return mixed
     */
    public function actionIndex()

    {
        $searchModel = new SearchAuthor();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionList()

    {
        $authors = Author::find()->with('books')->all();

        $this->view->title = 'List Authors and Books';
        return $this->render('list', [
            'authors' => $authors,
        ]);
    }

    /**
     * Displays a single author model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new author model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Author();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing author model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing author model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the author model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Author the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Author::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/BooksController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\BooksHistory;
use frontend\models\UploadForm;
use frontend\models\Books;
use frontend\models\SearchBooks;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\widgets\DetailView;

/**
 * BooksController implements the CRUD actions for Books model.
 */
class BooksController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Books models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SearchBooks();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $uploadForm = new UploadForm();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'uploadForm' => $uploadForm,
        ]);
    }

    /**
     * Displays a single Books model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Books model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Books();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $this->saveBookHistory($model);
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Books model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            $this->saveBookHistory($model);

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function saveBookHistory($model) {

        $bookHistory = new BooksHistory();
        $bookHistory->book_id = $model->id;
        $bookHistory->text = $model->text;
        $bookHistory->created_at = $model->updated_at;
        $bookHistory->save();
    }

    /**
     * Deletes an existing Books model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Books model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Books the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Books::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionAjax($id)
    {
        $model = $this->findModel($id);

        $hero = $model->hero;

        if (Yii::$app->request->isAjax) {

            if ($hero == null) {
                return "Hero not found";
            } else {
//                $hero = ("id: " . $hero->id . "\n"
//                    . "name: " . $hero->name . "\n"
//                    . "description: " . $hero->description . "\n"
//                    . "image: " . $hero->image . "\n"
//                    . "created_at: " . $hero->created_at . "\n");
//                return $hero;
                return DetailView::widget(['model' => $hero]);
            }
        }

        return $this->render('view', [
            'hero' => $hero,
        ]);
    }
}

frontend/controllers/CsvController.php
<?php

namespace frontend\controllers;

use Yii;
use Exception;
use frontend\models\Author;
use frontend\models\Books;
use frontend\models\UploadForm;
use yii\web\Controller;
use yii\web\UploadedFile;

class CsvController extends Controller
{
    /**
     * @return string
     */
    public function actionUpload()
    {
        try {

            $model = new UploadForm();

            if (Yii::$app->request->isPost) {
                $model->file = UploadedFile::getInstance($model, 'file');

                if ($model->file && $model->validate()) {
                    $model->file->saveAs(Yii::getAlias("@frontend/web/csv/") . $model->file->baseName . '.' . $model->file->extension);
                }
            }

            if (($handle = fopen("../web/csv/" . $model->file->name, "r")) !== FALSE) {
                while (($date = fgetcsv($handle, 1000, ",")) !== FALSE) {

                    if ($date[0] === "#" || $date[1] === "Appellation" ||
                        $date[2] === "Author Name" || $date[3] === "Created At") {

                        continue;
                    }

                    $books = new Books();

                    $books->appellation = $date[1];
                    $author = Author::find()->where(['name' => $date[2]])->one();
                    $books->author_id = $author->id;
                    $books->created_at = $date[3];
                    $books->save();
                }

                fclose($handle);
            }

        } catch (Exception $e) {
            echo 'import failed: ', $e->getMessage(), "\n";
            die();
        }

        return $this->render('upload', ['model' => $model]);
    }
}

frontend/views/books/_form.php
<?php

use frontend\models\Author;
use frontend\models\Hero;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\Books */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="books-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'appellation')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'text')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'author_id')->dropDownList(
        ArrayHelper::map(Author::find()->all(), 'id', 'name'),
        [
            'prompt' => '',
        ]
    ) ?>

    <?= $form->field($model, 'hero_id')->dropDownList(
        ArrayHelper::map(Hero::find()->all(), 'id', 'name'),
        [
            'prompt' => '',
        ]
    ) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>

        <?= Html::a('Backward', ['author/index'], ['class' => 'btn btn-danger']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/books/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\SearchBooks */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="books-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'appellation') ?>

    <?= $form->field($model, 'text') ?>

    <?= $form->field($model, 'author_id') ?>

    <?= $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/books/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\Books */

$this->title = 'Create book';
$this->params['breadcrumbs'][] = ['label' => 'Books', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="books-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/books/index.php
<?php

use kartik\dynagrid\DynaGrid;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\SearchBooks */
/* @var $dataProvider yii\data\ActiveDataProvider */
/**
 * @var \frontend\models\UploadForm $uploadForm
 */

?>
<div class="books-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php
    $columns = [
        ['class' => 'kartik\grid\SerialColumn', 'order' => DynaGrid::ORDER_FIX_LEFT],

        //'id',
        'appellation',
        //'text:ntext',
        //'author_id',
        'authorName',
        'created_at',
        //'updated_at',

        [
            'class' => 'kartik\grid\ActionColumn',
            'dropdown' => false,
            'order' => DynaGrid::ORDER_FIX_RIGHT
        ],
        ['class' => 'kartik\grid\CheckboxColumn', 'order' => DynaGrid::ORDER_FIX_RIGHT],
    ];
    ?>

    <?php
    $form = ActiveForm::begin([
        'action' => Url::to(['/csv/upload'])
    ]);

    echo $form->field($uploadForm, 'file')->fileInput();

    ?>
    <input type="submit" class="btn btn-primary" value="import">
    <?
    ActiveForm::end();
    ?>

    <?php
    echo DynaGrid::widget([
        'columns' => $columns,
        'storage' => DynaGrid::TYPE_COOKIE,
        'theme' => 'panel-danger',
        'gridOptions' => [
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'showPageSummary' => true,
            'panel' => [
                'heading' => '<h3 class="panel-title">  Books',
                'before'=>'{dynagrid}'/* . Html::a('import', '/csv/upload', ['class'=>'btn btn-primary'])*/,
            ],
        ],
        'options' => ['id' => 'dynagrid-1']
    ]); ?>

</div>

frontend/views/books/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\Books */

$this->title = 'Update Books: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Books', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="books-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/books/view.php
<?php

use yii\helpers\Html;
use yii\web\YiiAsset;
use yii\widgets\ActiveForm;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\Books */

$this->params['breadcrumbs'][] = ['label' => 'Books', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
YiiAsset::register($this);
?>
<div class="books-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'formatter' => ['class' => 'yii\i18n\Formatter','nullDisplay' => ''],
        'model' => $model,
        'attributes' => [
            'id',
            'appellation',
            'text:ntext',
            'author_id',
            'hero_id',
            'created_at',
            'updated_at',
        ],
    ]) ?>

    <div class="text-right">

        <?php $form = ActiveForm::begin() ?>

        <?= Html::submitButton('Show hero', ['class' => 'btn btn-success']); ?>

        <?php ActiveForm::end(); ?>

    </div>

    <div id="hero_data"></div>
    <?php
    $js = "
    $('form').on('beforeSubmit', function(){
        $.ajax({
            url: '/frontend/web/books/ajax',
            type: 'GET',
            dataType: 'html',
            data: {id : {$model->id}},
            success: function(data){
                $('#hero_data').html(data);
            },
            error: function(){
                alert('Error!');
            }
        });
        return false;
    });
";
    $this->registerJs($js);
    ?>

</div>

    <div class="text-left">

        <?php
        $history = $model->history;
        if ($history != null && count($history) > 1) { ?>
        <h1><?= Html::encode("Book History") ?></h1>
        <?php
        }?>

        <?php
            foreach ($history as $chapter) {

                if($model->updated_at == $chapter->created_at
                    || $chapter->text == null) {
                    continue;
                }

                echo '<H4>' . $chapter->created_at . '</H4></<br>';
                echo '<dl>' . $chapter->text . '</dl></<br>';
            }
            echo '</dl>'; ?>
    </div>